#!/bin/bash
# ============================================================================
# install.sh — turn the Jarvis stack into an always-on LAN service.
#
# Installs 4 launchd agents (auto-start at login, auto-restart on crash):
#   com.jarvis.livekit      LiveKit server, node-ip pinned to current LAN IP
#   com.jarvis.voiceserver  STT+TTS FastAPI server (:8005)
#   com.jarvis.agent        the voice agent worker (production `start` mode)
#   com.jarvis.netwatch     restarts livekit when the LAN IP changes
#
# Also: points the phone app at the Mac's stable mDNS name and bakes in a
# 10-year token, so it connects the moment both are on the same Wi-Fi and
# never suffers an expired-token or changed-IP outage.
#
# Re-runnable. No sudo required (the firewall already permits livekit-server).
# ============================================================================
set -euo pipefail

BACKEND="/Users/niranjan/Documents/livekitJarvis_2.0/agent-backend"
PROD="$BACKEND/production"
VENV_PY="$BACKEND/venv/bin/python"
APP_ENV="/Users/niranjan/Documents/livekitJarvis_2.0/assets/.env"
LA="$HOME/Library/LaunchAgents"
LOGS="$HOME/.jarvis/logs"
# launchd agents cannot exec/read shell scripts inside ~/Documents (TCC), so the
# scripts they invoke live here, outside the protected tree. Logs live here too.
SAFEBIN="$HOME/.jarvis/bin"
UID_="$(id -u)"
HOSTNAME_LOCAL="$(scutil --get LocalHostName).local"
LABELS=(com.jarvis.livekit com.jarvis.voiceserver com.jarvis.agent com.jarvis.netwatch)

echo "=========================================="
echo "  Jarvis production install"
echo "  mDNS host : $HOSTNAME_LOCAL"
echo "=========================================="

mkdir -p "$LOGS" "$LA" "$SAFEBIN"
# Copy the launchd-invoked scripts out of ~/Documents into the non-protected
# ~/.jarvis/bin so launchd can actually run them.
cp "$PROD/run_livekit.sh" "$PROD/netwatch.sh" "$SAFEBIN/"
chmod +x "$SAFEBIN/run_livekit.sh" "$SAFEBIN/netwatch.sh"

# ── 1. Stop anything started by hand or a previous install ──────────────────
echo "[1/6] Stopping existing services..."
for L in "${LABELS[@]}"; do
  launchctl bootout "gui/${UID_}/${L}" 2>/dev/null || true
done
pkill -f "livekit-server" 2>/dev/null || true
pkill -f "local_voice_server.py" 2>/dev/null || true
pkill -f "agent.py dev" 2>/dev/null || true
pkill -f "agent.py start" 2>/dev/null || true
sleep 1

# ── 2. Generate the long-lived token + rewrite the app .env ─────────────────
echo "[2/6] Generating 10-year token and updating app config..."
TOKEN="$("$VENV_PY" "$PROD/gen_token.py" my-room niranjan-phone 3650)"
cat > "$APP_ENV" <<EOF
# Auto-generated by production/install.sh — stable LAN config.
# URL is the Mac's mDNS name (resolves to its current IP on the same Wi-Fi).
# TOKEN is valid for ~10 years so the app never hits an expiry outage.
LIVEKIT_URL=ws://${HOSTNAME_LOCAL}:7880
LIVEKIT_API_KEY=devkey
LIVEKIT_API_SECRET=secret
LIVEKIT_TOKEN=${TOKEN}
EOF
echo "  wrote $APP_ENV  (LIVEKIT_URL=ws://${HOSTNAME_LOCAL}:7880)"

# ── 3. Write the launchd plists ─────────────────────────────────────────────
echo "[3/6] Writing launchd plists..."

write_plist() {  # $1=label  $2=workdir  $3...=ProgramArguments
  local label="$1"; shift
  local workdir="$1"; shift
  local plist="$LA/${label}.plist"
  {
    echo '<?xml version="1.0" encoding="UTF-8"?>'
    echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">'
    echo '<plist version="1.0"><dict>'
    echo "  <key>Label</key><string>${label}</string>"
    echo '  <key>ProgramArguments</key><array>'
    for a in "$@"; do echo "    <string>${a}</string>"; done
    echo '  </array>'
    echo "  <key>WorkingDirectory</key><string>${workdir}</string>"
    echo '  <key>RunAtLoad</key><true/>'
    echo '  <key>KeepAlive</key><true/>'
    echo '  <key>ThrottleInterval</key><integer>5</integer>'
    echo "  <key>StandardOutPath</key><string>${LOGS}/${label}.log</string>"
    echo "  <key>StandardErrorPath</key><string>${LOGS}/${label}.log</string>"
    echo '  <key>EnvironmentVariables</key><dict>'
    echo '    <key>PATH</key><string>/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>'
    echo '    <key>OLLAMA_KEEP_ALIVE</key><string>24h</string>'
    echo '  </dict>'
    echo '</dict></plist>'
  } > "$plist"
  echo "  $plist"
}

# Shell scripts run from /tmp: they use absolute paths and must NOT cwd into
# ~/Documents (bash's getcwd walks the TCC-protected parent chain and dies).
# The Python services DO need cwd=$BACKEND (relative imports, .env, model files).
# Shell scripts are launched as `/bin/bash <script>` (not exec'd directly):
# TCC blocks a launchd agent from EXECUTING a file inside ~/Documents, but bash
# (in /bin) may READ it — same reason the venv python (a symlink to /opt/homebrew)
# can read the .py files. cwd=/tmp so bash's getcwd never walks the protected tree.
# The Python services DO need cwd=$BACKEND (relative imports, .env, model files).
write_plist com.jarvis.livekit     "/tmp"     "/bin/bash" "$SAFEBIN/run_livekit.sh"
write_plist com.jarvis.voiceserver "$BACKEND" "$VENV_PY" "$BACKEND/local_voice_server.py"
write_plist com.jarvis.agent       "$BACKEND" "$VENV_PY" "$BACKEND/agent.py" start
write_plist com.jarvis.netwatch    "/tmp"     "/bin/bash" "$SAFEBIN/netwatch.sh"

# ── 4. Firewall: make sure livekit is allowed to receive connections ────────
echo "[4/6] Checking firewall (livekit-server incoming)..."
FW=/usr/libexec/ApplicationFirewall/socketfilterfw
if "$FW" --getappblocked "$(command -v livekit-server)" 2>/dev/null | grep -qi permitted; then
  echo "  livekit-server incoming already permitted."
else
  echo "  NOTE: run this once if the phone can't reach the Mac (needs admin):"
  echo "    sudo $FW --add \$(command -v livekit-server) --unblockapp \$(command -v livekit-server)"
fi

# ── 5. Boot the agents ──────────────────────────────────────────────────────
echo "[5/6] Bootstrapping launchd agents..."
for L in "${LABELS[@]}"; do
  launchctl bootstrap "gui/${UID_}" "$LA/${L}.plist" 2>/dev/null || \
    launchctl load "$LA/${L}.plist" 2>/dev/null || true
  launchctl enable "gui/${UID_}/${L}" 2>/dev/null || true
done

# ── 6. Status ───────────────────────────────────────────────────────────────
echo "[6/6] Status:"
sleep 3
for L in "${LABELS[@]}"; do
  if launchctl print "gui/${UID_}/${L}" >/dev/null 2>&1; then
    echo "  ✅ $L loaded"
  else
    echo "  ❌ $L NOT loaded"
  fi
done

echo ""
echo "=========================================="
echo "  Done. Services are now always-on."
echo "  App connects to: ws://${HOSTNAME_LOCAL}:7880  (room my-room)"
echo ""
echo "  ONE-TIME: rebuild the iOS app so it picks up the new"
echo "  assets/.env (stable mDNS URL + 10-year token). After that,"
echo "  no more reconfiguring — it just connects on the same Wi-Fi."
echo "  Logs: $LOGS"
echo "=========================================="
